apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: openapi1
  description: idk
  labels:
    example.com/custom: custom_label_value
  annotations:
    example.com/service-discovery: artistweb
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: apoenapi
  lifecycle: production
  owner: ria@gmail.com
  system: public-websites
  definition: 
    $text: https://github.com/Ria622/catalogue/blob/petstore-api/openapi.yaml
